language: node_js
node_js:
  - "0.10"

#  script: node_modules/karma/bin/karma start test/karma.conf.js --single-run

# Google Chrome
#
# https://github.com/travis-ci/travis-ci/issues/272#issuecomment-14402117
# http://stackoverflow.com/questions/19255976/how-to-make-travis-execute-angular-tests-on-chrome-please-set-env-variable-chr
#
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start


before_script:
 # - export DISPLAY=:99.0
  #- sh -e /etc/init.d/xvfb start
 - npm start > /dev/null &
  #- npm start
 - npm run update-webdriver
 - sleep 5 # give server time to start

script:
#- npm run test-single-run
#- npm run protractor
 #- node_modules/.bin/karma start karma.conf.js --no-auto-watch --single-run --reporters=dots
 - node_modules/.bin/protractor e2e-tests/protractor.conf.js
